### PR TITLE
[#1277] Add get/set Vector size utility

### LINKED ISSUE #1277: Add utility to get/set ex.Vector size
### Context
It would be useful to set the magnitude of a vector, this allows easy scaling or capping at a maximum value. This is especially useful in physics simulations.

### Proposal

I propose something like the following (there is probably a more efficient method of changing the size of the vector)

```typescript
  /**
   * The magnitude (size) of the Vector
   * @obsolete magnitude will be removed in favor `.size` in version v0.24.0
   */
  public magnitude(): number {
    return this.distance();
  }
  
 /**
  * The size (aka magnitude) of the Vector
  */
  public get size(): number {
    return this.distance();
  }

  public set size(newLength: number) {
    this.normalize().scale(newLength);
  }
```

Usage:

```typescript

const vel = new ex.Vector(3, 4);

console.log(vel.size); // 5
vel.size = 13;

// Automatically calculates to correct scale
console.log(vel.x); // 5
console.log(vel.y); // 12
```

### PR DESCRIPTION
**Pull request by saahilk**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/master/STYLEGUIDE.md)
- [ ] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [x] :page_facing_up: changelog entry added (or not needed)

==================

Closes #1277 

## Changes:

- Add get/set vector size utility
- Marked existing magnitude function as obsolete
- Updated CHANGELOG.md

### CODE REVIEW

**Comment by saahilk** [comment]
@eonarheim where do I put the unit tests?

**Comment by eonarheim** [comment]
@saahilk Yes please, `AlgebraSpec.ts`

**Comment by saahilk** [comment]
@eonarheim I wrote the following test for the setter, but for some reason the vector remains (20,0) even after setting it to 10. Any suggestions on this? 
  it('can have size set',() => {
    // eslint-disable-next-line no-var
    var v = new ex.Vector(20, 0);
    v.size=10;
    expect(v.x).toEqual(10);
    expect(v.y).toEqual(0);
  });

**Comment by eonarheim** [comment]
@saahilk Thanks for your contribution!

**Comment by saahilk** [comment]
@eonarheim Thanks for the opportunity. It was fun! :)

**Pull request merged**
