### PR TITLE
[#1317] Don't ramp volume when set at start of playback

### LINKED ISSUE #1317: Sound starting volume behaves incorrectly
### Steps to Reproduce
```typescript
sound.play(0.1);
```

### Expected Result
Sound plays at 10% gain.

### Actual Result
 * On platforms that support Web Audio: Sound starts playing at 100% gain, then ramps down to 10% over the course of around 0.2 seconds.
 * On other platforms: Sound plays at 10% gain as expected.

### Environment
- browsers and versions: Chrome 77
- operating system: Windows 10
- Excalibur versions: 0.23.0
- (anything else that may be relevant) 

### Current Workaround
None known.

### PR DESCRIPTION
**Pull request by djcsdy**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/master/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [ ] :page_facing_up: changelog entry added (or not needed)

==================

Closes #1317

## Changes:

- Only apply volume ramp if sound is already playing.

### CODE REVIEW

**Comment by djcsdy** [comment]
This is a wip since the existing tests no longer pass.

**Comment by eonarheim** [comment]
This makes sense to me, I don't see a problem merging after the existing tests are addressed

**Comment by djcsdy** [comment]
This is ready for review now.

**Comment by eonarheim** [comment]
@djcsdy Thanks for the contribution!

**Pull request merged**
