### PR TITLE
Final review release prep

### PR DESCRIPTION
**Pull request by eonarheim**
Hi all,

Please pull down the release prep branch and ensure everything is working with your games. This is the final candidate for release!!! :D 

If you find any breaking changes between the 0.5.1 -> 0.6.0 upgrade let me know, I'll do my best to document any I'm aware of.

### CODE REVIEW

**Comment by kamranayub** [comment]
Should we upgrade Minotaur as a test case?

**Comment by eonarheim** [comment]
Probably a solid idea!

**Comment by kamranayub** [comment]
A few things we found when upgrading Minotaur:

- `addChild` and `removeChild` have been renamed to `add` and `remove` on Actors
- `isKeyPressed` has been renamed to `isHeld` on Keyboard
- Label `font` property is not handled correctly with font sizing

Centering was fixed which caused a bug due to us working around it.

**Comment by eonarheim** [comment]
We are ready!

**Comment by kamranayub** [comment]
:fireworks:

**Comment by eonarheim** [comment]
:shipit:

**Pull request merged**
