### PR TITLE
Support wrapping ex.Text graphics

### LINKED ISSUE #2463: Support wrapping ex.Text graphics
### Context

Currently it is not possible to wrap text graphics inside a bounding box without some manual intervention or custom code.

See discussion for more context https://github.com/excaliburjs/Excalibur/discussions/2458#discussioncomment-3393549

### Proposal

Implement simple text wrapping given a optional maximum width or an optional containing bounding box.

Perhaps `ex.Text.maxWidth` or `ex.Text.textContainer`?

```typescript
const text = new ex.Text({
  ...
  maxWidth: 200 // pixels
});
``` 

```typescript
const text = new ex.Text({
  ...
  textContainer: ex.BoundingBox.fromDimension(200, 200); // 200x200 box
});
```

### PR DESCRIPTION
**Pull request by RyanGrieb**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/main/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [x] :page_facing_up: changelog entry added (or not needed)

==================

Closes #2463

## Changes:

- Add ```maxWidth``` TextOption to support word wrapping

Hi, I think I've progressed enough to post a draft PR. 
Currently wrapping works when the ```maxWidth``` option is provided for the ex.Text class.

There is a bug currently where text > 2 lines isn't rendered since I don't update the ```ex.Text``` height properly when we word wrap. 
If there is any other outstanding problems in the code/PR please let me know!

Screenshot_2022-08-27_15-08-35

### CODE REVIEW

**Comment by eonarheim** [comment]
@RyanGrieb thanks for the PR! I'll have some time to look this over this week sometime👍

**Comment by eonarheim** [comment]
@RyanGrieb the code looks good to my eyes! Exactly what I would have expected

There is one failing test, I'm trying to figure out why the text generated is slightly shifted up and to the left. It might be the case that the new changes are more correct, I'm just not sure why it's different quite yet.

image

**Comment by eonarheim** [comment]
@RyanGrieb Actually! I believe the PR code is more correct the `resetTransform()` prevents the context transform from being corrupted with previous calls to `_applyFont()` which is a problem in the current main branch. Many thanks!

I think this PR is ready, update the failing test, add a new test for the maxWidth, and fix the height issue you spoke about 👍

**Comment by RyanGrieb** [comment]
@eonarheim I believe corrected the height issue. I'm not sure how you'd like me to correct the failing test. Should I replace the image? Also, how would I individually run the test 722 and visually look at it.
image
Looking good :smile:
Once I fix the failing test I'll complete the rest of the PR checklist & merge the separate commit messages.

**Comment by RyanGrieb** [comment]
Also I haven't tested this w/ ```ex.SpriteFont```. I don't think we should merge until I look at it & test it properly.

**Comment by eonarheim** [comment]
> I'm not sure how you'd like me to correct the failing test. Should I replace the image? Also, how would I individually run the test 722 and visually look at it.

@RyanGrieb good questions! 

Yes please do replace the expected test images if you can (you can copy paste the base64 image into a browser and download it to the appropriate spec in `src/spec/images` folder). You can grab the expected linux image from the failing test in the github action, but if you don't have a windows machine I can add a commit to your fork with expected windows image 👍 

You can add an `f` to the front of the [test](https://github.com/excaliburjs/Excalibur/blob/2e57d35a9d689495f6f52e1b01b728af52abeb75/src/spec/TextSpec.ts#L639) `it` to "focus" the test and only run that one `fit('can reuse a font', async () => {`.

Really appreciate the work on this feature! It'll be a huge value add to Excalibur!

**Comment by RyanGrieb** [comment]
Word wrap for sprite font added, add changelog entry
image
Weird spacing on the left side though, not sure if it's supposed to be like this.

**Comment by eonarheim** [comment]
@RyanGrieb This is looking great! Let me know when you're ready for review

> Weird spacing on the left side though, not sure if it's supposed to be like this.

@RyanGrieb I think that's expected with the `SpriteFont` by default in the current implementation. The `SpriteFont` image has some extra padding in the individual sprites per glyph. Although there may be a case for adjusting the first letter offset in addition to specifying the `spacing`, but I think that would be best in a separate issue/PR 👍 

image

**Comment by eonarheim** [comment]
Hi @RyanGrieb sorry about the delay on this PR! Life happened to me!

Is it okay if I push a few commits to your fork? This is definitely something that would be nice to include in the next release of excalibur!

**Comment by RyanGrieb** [comment]
@eonarheim Go for it. I couldn’t get tests working for some reason on my machine.

**Comment by eonarheim** [comment]
@RyanGrieb Thanks for working on this feature! Sorry about the long delay on the merge! 

We appreciate the hard work this is great feature!

**Pull request merged**
