### PR TITLE
feat: [#2460] add support for wasButtonPressed and wasButtonReleased

### LINKED ISSUE #2460: Support "wasPressed" and "wasReleased" for Gamepad input
### Context

It would be helpful if `engine.inputs.gamepad` supported `wasPressed` and `wasHeld` the same way `engine.inputs.keyboard` does.  This would make it easier to interchangeably support keyboard or gamepad input.

### Proposal

Add `wasPressed(button)` and `wasReleased(button)` to gamepad input API. Perhaps rename `isButtonPressed()` to `isButtonHeld()` to closer match keyboard API (`isKeyHeld()`)

### PR DESCRIPTION
**Pull request by mattjennings**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/main/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [x] :page_facing_up: changelog entry added (or not needed)

==================

Closes #2460

## Changes:

- add support for gamepad wasButtonPressed and wasButtonReleased

### CODE REVIEW

**Comment by mattjennings** [comment]
@eonarheim let me know what you think of these changes. I didn't see any existing gamepad test suites for `isButtonPressed` - only a sandbox, so I updated that instead.

This doesn't contain the proposed change of renaming `isButtonPressed` to `isButtonHeld` as I'm not sure if we're in favour of that or not.

**Comment by eonarheim** [comment]
@mattjennings That's fine, the sandbox should be okay since there are no unit tests (and I'm not positive how I would unit test the GamePad API either)

I mentioned in the issue, but I'm in favor of the name change for consistency 👍 we can mark the old name `@deprecated` in the jsdoc and changelog.

**Comment by mattjennings** [comment]
@eonarheim perfect, should be good to go now!

**Review by eonarheim — APPROVED** [review]
@mattjennings Looks awesome! Thanks again!

**Pull request merged**
