### PR TITLE
Update Algebra.ts Infinity vectors test

### PR DESCRIPTION
**Pull request by Carghaez**
Update Algebra.ts Infinity vectors test with all cases

### CODE REVIEW

**Comment by eonarheim** [comment]
Hi @Carghaez, thanks for contributing!

Please move these changes to your first branch `patch-1` to include in this PR #1004. This way we can keep all the changes related to this fix in one PR.

`git checkout patch-1`
`git merge patch-3`
`git push origin patch-1`

**Comment by Carghaez** [comment]
Uhm, i've done that changes throw github website from my phone, idk if it is possible to do some stuff to merge that pull request without a repo.

I do some research

**Comment by eonarheim** [comment]
@Carghaez I've had trouble with phone based stuff before, there is no rush.

You'll need to run these commands on your local fork of Excalibur, the PR #1004 should update automatically as soon as new commits are pushed to the `patch-1` branch.

**Comment by Carghaez** [comment]
Done! :dancer:

**Comment by eonarheim** [comment]
Awesome! I'll close this PR in favor of #1004 💃 

Thanks for helping!

**Pull request closed without merging**
