### PR TITLE
fix: [#2374] Karma tests on M1 macs

### LINKED ISSUE #2374: Karma tests fail on M1 Macs
Relavant discussion - https://github.com/excaliburjs/Excalibur/discussions/2372

The karma test suite currently fails on Macs using M1 chips due to various webgl errors. Switching from Chrome to Chromium fixes this.

### Steps to Reproduce

Run `npm run test` on a Mac with M1 chip

### Expected Result

tests to pass

### Actual Result

about ~80 tests fail with an error like:

```
Chrome Headless 99.0.4844.0 (Mac OS 10.15.7) A VertexBuffer can bind a buffer FAILED
        Error: Failed to retrieve webgl context from browser
            at new ExcaliburGraphicsContextWebGL (/var/folders/zf/t18x1b8s31s64l4hcxgdbl240000gn/T/_karma_webpack_504653/commons.js:2507:67239)
            at UserContext.<anonymous> (/var/folders/zf/t18x1b8s31s64l4hcxgdbl240000gn/T/_karma_webpack_504653/commons.js:25443:22)
            at <Jasmine>
        Error: Attempted gl access before init
            at Function.get gl [as gl] (/var/folders/zf/t18x1b8s31s64l4hcxgdbl240000gn/T/_karma_webpack_504653/commons.js:2779:3191)
            at new VertexBuffer (/var/folders/zf/t18x1b8s31s64l4hcxgdbl240000gn/T/_karma_webpack_504653/commons.js:2847:8327)
            at UserContext.<anonymous> (/var/folders/zf/t18x1b8s31s64l4hcxgdbl240000gn/T/_karma_webpack_504653/commons.js:25468:21)
            at <Jasmine>
```

### Environment

- browsers and versions: Chrome Headless 99.0.4844.0 & Node 16
- operating system: macOS 12.4
- Excalibur versions: 0.26
- (anything else that may be relevant)

### PR DESCRIPTION
**Pull request by mattjennings**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/main/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [x] :page_facing_up: changelog entry added (or not needed)

==================

Closes #2374

## Changes:

- uses Chromium for karma tests instead of Chrome

### CODE REVIEW

**Comment by mattjennings** [comment]
er, I guess this is technically a "chore" - let me know if you want me to change the commit message.

**Comment by mattjennings** [comment]
eek, I see the tests are failing. Interestingly, those test failures are _exactly_ what I was seeing with Chrome on M1 :S

**Comment by eonarheim** [comment]
@mattjennings That is interesting, I should theoretically be able to reproduce this in a linux container locally. I'll give that a shot. 

I'm confused why chromium/chrome would render differently in linux but not on the M1, it might be some of our command line flags behave different, or perhaps linux chromium behaves differently (which would be really sad)? 

On you local system with chromium does karma still report "Chrome Headless"?
image

**Comment by mattjennings** [comment]
@eonarheim whew, what a journey! Thanks for taking a deeper look and tracking it down.

**Comment by eonarheim** [comment]
If it's okay with you I'll close this PR in favor of https://github.com/excaliburjs/Excalibur/pull/2373, I had to make the same changes you did in addition to rev-ing puppeteer and fixing the tests.

I'll be sure to credit you in the release notes 👍

**Comment by mattjennings** [comment]
oh yeah, no problem at all!

**Pull request closed without merging**
