### PR TITLE
[Closes #412] Update documentation to comply with TypeDoc

### LINKED ISSUE #412: Update code remove unused jsdoc tags and comply with TypeDoc
- [x] Switch `{#crosslink}` to `[[]]`
- [x] Remove redundant type metadata
- [x] Add top-level module documentation

### PR DESCRIPTION
**Pull request by kamranayub**
Closes #412 

I've also added additional docs for some classes like `Logger`, `TileMap`, etc.

Merge when ready!

### CODE REVIEW

**Comment by kamranayub** [comment]
So one change I made was this method in `Actor.setDrawing`:

```ts
    public setDrawing(key: string) {

         if (this.currentDrawing != this.frames[<string>key]) {
            this.frames[key].reset();
         }
         this.currentDrawing = this.frames[key];
      }
```

It used to be:

```ts
    public setDrawing(key) {

         if (this.currentDrawing != this.frames[<string>key]) {
            this.frames[<string>key].reset();
         }
         this.currentDrawing = this.frames[<string>key];
      }
```

The reason was so you could pass enums without issues (numbers). Should that still be allowed? If so, maybe this would be better then:

```ts
    public setDrawing(key: any) {
         key = key.toString();

         if (this.currentDrawing != this.frames[key]) {
            this.frames[key].reset();
         }
         this.currentDrawing = this.frames[key];
      }
```

**Comment by kamranayub** [comment]
@eonarheim if you're cool with that change, I can merge.

**Comment by eonarheim** [comment]
@kamranayub I like it, go forth

**Comment by kamranayub** [comment]
Merge baby merge :rocket:

**Pull request merged**
