### PR TITLE
[#521] Implement Image Diff Testing in Excalibur

### LINKED ISSUE #521: Image diff regression testing
We have implemented a number of visual "test-like" demos [(/sandbox/web/tests)](https://github.com/excaliburjs/Excalibur/tree/master/sandbox/web/tests) for elements of Excalibur that are difficult to unit test. Ideally, these should be re-implemented as automatic regression tests using some sort of canvas testing framework. Options include, but are not limited to, the list below.
- https://humblesoftware.github.io/js-imagediff/
- https://github.com/platfora/Canteen

### PR DESCRIPTION
**Pull request by eonarheim**
Closes #521

## Proposed Changes:

- Fix code coverage calculations, while working this issue it was discovered that our current testing process incorrectly reported higher than actual code coverage 😭
- Implement a PhantomJS based testing harness to run our existing Jasmine tests
- Implement image diff testing matchers using a modified version of (js-imagediff)[https://github.com/HumbleSoftware/js-imagediff], see an example in `UIActorSpec.ts`
image

- Local debugging experience is preserved in vscode with the PhantomJS Debugger extension
image

## Next Steps:

- Replace as much mocked draw code with actual tests as possible
- Publish our modified version of js-imagediff with new Jasmine 2.x+ browser canvas matcher implementation

### CODE REVIEW

**Comment by eonarheim** [comment]
The build is failing because of npm peer dependency mismatch, please review the changes while I get to the bottom of the npm sadness before merging

**Comment by kamranayub** [comment]
Can you enumerate any new contributor prerequisites and add to our contributing section? e.g. we now need another plugin in VS code to do debugging. Also any versions required.

**Comment by eonarheim** [comment]
@jedeen @kamranayub Please review my new changes and see if you have anything I should add/change/remove

**Comment by eonarheim** [comment]
@jedeen Are there more change you'd like?

**Pull request merged**
