### PR TITLE
Added strict compiler flags - Issue #724

### PR DESCRIPTION
**Pull request by asi7296**
## Changes:

- Added the following compiler flags in `tsconfig.js` :

```
noImplicitAny: true
noFallthroughCasesInSwitch: true
noImplicitReturns: true
noImplicitThis: true
noUnusedLocals: true
noUnusedParameters: true
```

( The indentation appears fine in Sublime Text 3, but looks messed up on the GitHub viewer )

### CODE REVIEW

**Comment by asi7296** [comment]
I've forked the repo, made changes and created a pull request.
This is my first time contributing to an open source project, so please let me know if there are other rules to contribute to this project, along with changes needed in the code, if any.

**Comment by kamranayub** [comment]
Thanks for contributing! We'd love to accept this PR. Since TypeScript is a compiled language, enabling these flags will result in changes having to be made throughout the codebase.

If you feel up to it, you can take a stab at fixing the compiler errors! If you don't feel up to it, we'd welcome help on any of our other jump-in tasks that are smaller. You can close this PR if so.

In the readme is all the info needed to test out changes locally and once the PR is ready we'd do some additional tests too.

Thanks! 👍

**Comment by asi7296** [comment]
Please take a look at the errors.
I've fixed most of them, there are 11 remaining, and I don't know how to  fix them.
Some need a different implementation of a particular entity, eg. a json to be implemented as a class, 
and some require error handling (function return values in case of error), and I'm not sure what the standard for this project is.
Thanks.

**Comment by kamranayub** [comment]
Thanks! We can definitely help you out here. One of us will pull down your changes and look through the remaining errors.

**Comment by kamranayub** [comment]
I took a look and fixed a couple issues that you mentioned. I also noticed there are actually a lot *more* errors but `grunt-ts` plugin was hiding them, so I fixed that and now there are 138 errors.

You can pull in my changes from the asi7296-master branch, since I can't make changes on this PR directly.

**Comment by asi7296** [comment]
I'll continue working on fixing the errors, through the asi7296-master branch on this repo.
Thank you!

**Comment by eonarheim** [comment]
@asi7296 Please let us know if you're still working on this PR, otherwise we will close it soon and take over the issue.

Let us know if you have any questions.

Thanks!

**Comment by asi7296** [comment]
@eonarheim 
I'm sorry about the delay, been caught up with college, please do close the request, I will not be able to work on it for a while.
I'd like to contribute to this project in the future though, if that's alright?
Thanks for all the help.

**Comment by kamranayub** [comment]
Thanks for letting us know, one of us can take it over. Thanks for
contributing!

**Comment by eonarheim** [comment]
@asi7296 Please contribute again

**Pull request closed without merging**
