### PR TITLE
[#612] Add position vector to PositionEvent

### LINKED ISSUE #612: Add position vector to ex.Input.PointerEvent
### Context

`ex.Input.PointerEvent` contains `x` and `y` properties because that is what the W3C spec says MouseEvent should have but to be consistent within Excalibur's API, it should just be a `pos` Vector with the same values.

Look at other events to ensure it's consistent.
### Proposal
1. `@deprecate` `x` and `y`
2. Add `pos` vector instead

This will be a breaking change when `x` and `y` are removed.

### PR DESCRIPTION
**Pull request by Crizzooo**
Closes #612

## Changes:

- `PointerEvent` now initiates `pos` property to a Vector using `x` and `y` args

### CODE REVIEW

**Comment by Crizzooo** [comment]
@kamranayub X and Y are still public and accessible on PointerEvent. Are we leaving them there or would you like them to be removed as properties as only come in as arguments? I'd imagine that is breaking.

**Comment by kamranayub** [comment]
Hmm, I'll let some others chime in... We are usually okay with breaking
changes since we are still pre-1.0... or we can mark things obsolete using
decorators.

**Comment by jedeen** [comment]
@kamranayub Generally we've been marking things as obsolete, letting that annotation sit for one release, then removing the items from the API in the following release.

**Comment by eonarheim** [comment]
Agreed, let's mark the `x`, and `y` as obsolete in favor of the `.pos` on the pointer

**Comment by kamranayub** [comment]
OK, you can just add `@obsolete` to the JSdoc on the parameters!

**Comment by Crizzooo** [comment]
Was just reading JSdoc's documentation for the first time, is @obsolete different from @deprecate? I do not see obsolete [herel](http://usejsdoc.org/index.html)

**Comment by kamranayub** [comment]
It's the same but for us, we use special styling in the docs to show
deprecation notices. Sorry, holdover from our C# background where we use
Obsolete

**Comment by Crizzooo** [comment]
@kamranayub Updated with the @deprecated tags. Do we want to fully remove x and y from being properties on pointerEvent?  If I drop the public tags, the apidocs will not compile, so I have left it as is.

**Comment by kamranayub** [comment]
@Crizzooo that's interesting, we've never tested using the `@deprecated` param so I'm interested to see what gets built in the docs. We can leave as-is, we are just deprecating, not removing the parameters outright yet.

**Comment by Crizzooo** [comment]
@kamranayub Not sure if I was supposed to click 'update branch' or not. I am unsure of how my master in this repo lines up with Excalibur repo or why pointerEvent branch even cares about master?

**Comment by kamranayub** [comment]
@Crizzooo Yes that's right, it's because for a PR to merge to be allowed the branch must be completely up-to-date with master to avoid merge conflicts. Everything looks good, I'll let @eonarheim give it a once over before merging.

**Comment by eonarheim** [comment]
@Crizzooo Hi, I think you may have accidently deleted your PR branch. Github can't merge the changes since the source branch no longer exists in your fork of the repo https://github.com/Crizzooo/Excalibur.git 

image


```shell
$ git checkout -b Crizzooo-pointerEvent master
Switched to a new branch 'Crizzooo-pointerEvent'
$ git pull https://github.com/Crizzooo/Excalibur.git pointerEvent
fatal: Couldn't find remote ref pointerEvent
```

If you still have the branch locally you could re-push it to your fork, otherwise you may need to recreate your pull request using the cached commits in github:

https://github.com/excaliburjs/Excalibur/pull/814/commits/3cc17bb51c002e623301a807c8cebafef9e3bd82,
https://github.com/excaliburjs/Excalibur/pull/814/commits/bb564a8c24a1d6d5b1e00bb5f39aaeb2eeb2e7fe,
https://github.com/excaliburjs/Excalibur/pull/814/commits/132e1675fdfbcb06b06393d25fef7bb7c0455828

**Comment by kamranayub** [comment]
Closing for now, will re-open when fixed (when the branch is back, this should work)

**Pull request closed without merging**
