### PR TITLE
Cleaned up code and tests removing .extends() in Class.ts to resolve Issue #1276

### LINKED ISSUE #1276: Remove obsolete .extend() semantics in Excalibur
### Context
Browsers natively support ES6 classes, there is no need for a custom inheritance scheme in Excalibur. For any future down level support we should point people to tools like babel/TypeScript.

### Proposal

Remove these lines of code 
and any associated tests or documentation around it.
https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Class.ts#L60-L122

### PR DESCRIPTION
**Pull request by Guzzler**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/master/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [x] :page_facing_up: changelog entry added (or not needed)

==================

Closes #1276 

## Changes:

- Removed the L60-L122 as mentioned in Issue #1276 
- Deleted ClassSpec that used the .extends() functionality

### CODE REVIEW

**Comment by Guzzler** [comment]
The changeLog change has not been added but i am not sure if this change requires it. Please let me know if so and i will do the needful.

**Comment by eonarheim** [comment]
@Guzzler Please add an entry under 
`## [Unreleased]` a `Breaking Changes` section for this

**Comment by Guzzler** [comment]
This has been completed @eonarheim with the changeLog additions! Thanks!

**Comment by eonarheim** [comment]
@Guzzler Thanks for your contribution!

**Pull request merged**
