### PR TITLE
[#97] Add basic frame statistics

### PR DESCRIPTION
**Pull request by kamranayub**
Part of #97

To make our way towards closing #97 we need basic statistics to gather and display. This adds some basic frame statistics that are collected during a frame and is designed to be extended later on with more stats. Since all stats are encapsulated in a class, users can add historical tracking and logging of past statistics using the `preframe` and `postframe` hooks on engine.

## Proposed Changes:

- Add `Engine.debug` to access current frame stats and (later) provide debugging flags/functions
- Add `Engine.stats.currFrame` and `Engine.stats.prevFrame` to hold current and previous frame statistics
- Add new `FrameStats` class to hold frame statistics
- Add new `postframe` and `preframe` events which fire before and after the frame is drawn/updated to aid in stat display/collection

### CODE REVIEW

**Comment by kamranayub** [comment]
Thoughts on the names for `currentFrameStats` and `prevFrameStats`? I am leaning towards renaming to `currFrameStats` and `lastFrameStats` (Current and Last, vs. Next and Previous). I would also be willing to entertain something like `Engine.stats.current` and `Engine.stats.last`.

Also I think I need to fix the visual test as now that I think about it, the engine reuses the two instances to keep memory overhead low--so to do historical, I have to "clone" them otherwise the instances will change.

**Comment by alanag13** [comment]
"previous" is more clear than "last" (one could argue that the current frame is last chronologically). I would go curr/prev for brevity's sake and do something like `Engine.stats.currFrame` and `Engine.stats.prevFrame` to allow for possibility of extending `Engine.stats` to include things beyond just frame statistics (e.g. perhaps game or scene).

**Comment by kamranayub** [comment]
@alanag13 I wonder since I already have a `debug` property on Engine and it shortcuts to the current frame stats, if I should simply add current and previous frame stats to that object vs. creating a new stats holder on Engine?

**Comment by alanag13** [comment]
@kamranayub  I agree that you probably don't want a whole new holder. Could you do that and just have `Engine.stats` be an alias for `Engine.debug.stats`? Basically I'm making an argument that the term 'debug' doesn't always apply when trying to get at these (although sometimes it does). Small usability/discoverability thing. If we do expand stats we could just do it on the `Engine.debug` object then.

**Comment by kamranayub** [comment]
Alright, fixed some bugs, verified with tests, we should be good.

**Pull request merged**
