### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by djcsdy**
===:clipboard: PR Checklist :clipboard:===

- [ ] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/master/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [ ] :page_facing_up: changelog entry added (or not needed)

==================

## Changes:

I'm working through Excalibur fixing typos as I find them. For safety I won't modify any code, just documentation and comments.

### CODE REVIEW

**Comment by eonarheim** [comment]
@djcsdy Thanks for all the typo fixes so far! 

We briefly looked into an automatic comment spellchecker a few years ago and didn't find anything that worked for us at the time. We'd be interested in any recommendations you have around automatically fixing typos.

**Comment by djcsdy** [comment]
@eonarheim I am using the cspell plugin for VSCode to find and fix these. It is also possible to run cspell from the command line, see https://www.npmjs.com/package/cspell

**Comment by eonarheim** [comment]
@djcsdy Let me know when you're ready for review/merge. Looks good to me so far 👍

**Comment by djcsdy** [comment]
@eonarheim This is ready for review and merge now.

**Pull request merged**
