### PR TITLE
[chore] [docs] Fix breakout ball collision step

### PR DESCRIPTION
**Pull request by clofresh**
If you're following along with the quickstart guide, after the step
where you add the ball, it says the ball will bounce off of the paddle
but it doesn't until you've added the precollision handler later on
in the tutorial.

This change adds the precollision handler when adding the ball, then
updates it later for breaking the bricks.

### CODE REVIEW

**Comment by eonarheim** [comment]
@clofresh Good catch! Thanks!

**Comment by Vyeche** [comment]
Hi, it seems its broken in version "0.31.0" ... The ball goes right through.

**Comment by eonarheim** [comment]
@Vyeche Oh no! Thanks for the comment on this, investigating now

**Comment by eonarheim** [comment]
@Vyeche I've pushed a fix

`other` is now a Collider type https://github.com/excaliburjs/sample-breakout/commit/71e311c2dd43648b6121a321d11d26315d9935be#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3d

image

**Comment by eonarheim** [comment]
@Vyeche Looks like the tutorial docs were updated to be correct  https://github.com/excaliburjs/Excalibur/blob/main/site/docs/00-tutorial/00-breakout.mdx

Let me know if you spot anything else!

image

**Comment by Vyeche** [comment]
Yep the code changed fixed the issue of it skipping the bounce off the bar.

**Pull request merged**
