### PR TITLE
[#1096] Add flag to IEngineOptions to set canvas transparency

### LINKED ISSUE #1096: Add flag to IEngineOptions to set canvas transparency
### Context
Currently excalibur does not expose a way to enable/disable canvas transparency, see https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#Turn_off_transparency.

We can save some processing by defaulting to a non-transparent canvas (which is a rare case)

### Proposal
* [ ] Add an additional property to `IEngineOptions` called `enableCanvasTransparency` that will can enable/disable canvas transparency
* [ ] Default excalibur's canvas context to NOT be transparent by default when creating the graphics context `canvas.getContext('2d', { alpha: false });`

### PR DESCRIPTION
**Pull request by edualb**
===:clipboard: PR Checklist :clipboard:===
- [x] :pushpin: issue exists in github for these changes 
- [x] :microscope: existing tests still pass
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [x] :page_facing_up: changelog entry added (or not needed)

==================

Closes #1096

## Changes:

- Added `enableCanvasTransparency` property that will can enable/disable canvas transparency
- Updated default Engine options.

### CODE REVIEW

**Comment by jedeen** [comment]
Hello! I would try leaving the canvas transparency enabled by default for now. This should allow the existing tests to pass and let you to write new tests for this feature. We can re-disable the transparency once we've updated the existing tests. Thanks!

**Comment by eonarheim** [comment]
Agreed, we will want to preserve backwards compatibility so defaulting transparency to `true` is ideal.

**Comment by edualb** [comment]
I'm sorry for being late @eonarheim  and @jedeen. I setted the `enableCanvasTransparency = true` and all tests passed.

**Comment by eonarheim** [comment]
@edualb Thanks for contributing!

**Pull request merged**
