### PR TITLE
[#639] Add helpful event types on event handlers

### LINKED ISSUE #639: List possible event types as a type union in handlers
Currently it is difficult to know what events are emitted by default on types in excalibur, typescript has a new string type union feature that can help.

#### Proposal
List all events on top level excalibur objects
- [x] Actors
- [x] Engine
- [x] Scene
- [x] Pointer
- [x] Keyboard
- [x] GamePad?

Add type union of possible events

```typescript

namespace events {
    export type click = "click";
    export type down = "down"; 
    export type all = click | down;
}
function emit(event: events.all | string) {
	// emit event
}

function on(event: events.all | string, handler: (any)=>any){
	// handle event
}

```

### PR DESCRIPTION
**Pull request by eonarheim**
Closes #639

Adds some convenient pre-loaded typed overloads to the `.on(...)` event handlers registration methods. This makes it easier for folks to know what available built in event types exist in Excalibur, making the api easy to discover from a typed tooling perspective.

## Proposed Changes:

- Add `ex.Events.<eventName>`
- Add overloads for 
   - [x] Actor
   - [x] Scene
   - [x] Engine
   - [x] Keyboard
   - [x] Pointer
   - [x] GamePad
- Add tests

### CODE REVIEW

**Comment by eonarheim** [comment]
I will merge master and update the changelog as soon as the #645 and #646 are merged

**Comment by eonarheim** [comment]
@excaliburjs/core-contributers Please review

**Comment by kamranayub** [comment]
Looks good :+1:

**Comment by eonarheim** [comment]
Mergin' :shipit:

**Pull request merged**
