### PR TITLE
docs: #3132 Update all Markdown comment symbol links to {@apilink}

### LINKED ISSUE #3132: docs: Update all engine source code Markdown comment symbol links to `{@apilink}`
We need to go around and fix up all the Markdown symbol links in the engine source code so they get rendered properly in the docs API site.

### Steps to Reproduce

On API pages, links between API symbols used to be done using the legacy symbol markup:

```
This is a link to the [[Actor]] class.

This is a link to the [[Actor|actor]] class with custom display text.
```

These should all be switched to `{@apilink symbol | text}` links ([docs](https://www.npmjs.com/package/docusaurus-plugin-typedoc-api#apilink)).

You can refer to `src\engine\Actions\ActionContext.ts` for an example that works.

> **NOTE:** Using the official `{@link}` tag [doesn't quite work as expected](https://github.com/milesj/docusaurus-plugin-typedoc-api/issues/66#issuecomment-2239524493) all the time, so for consistency I recommend `@apilink`.

### Expected Result

The links should work.

**Example:**

image

### Actual Result

The links are rendered in plaintext.

**Example:**

image

### PR DESCRIPTION
**Pull request by Autsider666**
Used the following setup to search for and replace the Markdown comments:
Search: `\[\[([a-zA-Z 0-9._]*)\|([a-zA-Z 0-9._]*)\]\]` and `\[\[([a-zA-Z 0-9._]*)\]\]`
Replace: `{@apilink $1 | `$2`}` and `{@apilink $1}`

I wasn't sure if all the "normal" comments had to be replaced as wel, because `src/engine/Actions/ActionContext.ts` contains both `{@apilink Action}` and `[[EasingFunctions]]`. It's easy to do with a small modification, so give me a shout if that's preferred.

Closes #3132

### CODE REVIEW

**Comment by kamranayub** [comment]
Yes all the [[link]] variations need to be replaced as well! 

The only thing we will need to do is spot check all the references to make sure they are resolved as well. By default the build will not fail if the resolution is missing and it'll output plain text.

**Comment by eonarheim** [comment]
@kamranayub Yah, I think I'll pull it locally. Currently the automation isn't running on forks

**Comment by kamranayub** [comment]
@Autsider666 Oops, the changes should only be done in `src/engine` folder. `site` docs doesn't have this problem. 👍

**Comment by Autsider666** [comment]
I reverted the changes in `site`, also replaced the `[[link]]` variants and scoured the code for weird edgecases (like `[[CoordPlane|coordinate plane|]]` in `TransformComponent`). Took the liberty to remove the last `ex.` used in these links as well.

Now I just have 1 question left: What about this example in CONTRIBUTING.md?
```ts
/** @deprecated use [[SomeClass]].someNewFunction instead **/
@obsolete({message: 'ex.SomeClass.someFunction is deprecated, and will be removed in 0.2.0',
	alternateMethod: 'SomeClass.someNewFunction'})
public someFunction() {...}
```

**Comment by eonarheim** [comment]
> I reverted the changes in `site`, also replaced the `[[link]]` variants and scoured the code for weird edgecases (like `[[CoordPlane|coordinate plane|]]` in `TransformComponent`). Took the liberty to remove the last `ex.` used in these links as well.
> 
> Now I just have 1 question left: What about this example in CONTRIBUTING.md?
> 
> ```ts
> /** @deprecated use [[SomeClass]].someNewFunction instead **/
> @obsolete({message: 'ex.SomeClass.someFunction is deprecated, and will be removed in 0.2.0',
> 	alternateMethod: 'SomeClass.someNewFunction'})
> public someFunction() {...}
> ```
> 
> Edit: Isn't it supposed to be `[[SomeClass.someNewFunction]]` by the way?

Awesome, yes I think you're right.

I'll run this locally quick to double check everything looks good before merge

**Review by eonarheim — APPROVED** [review]
@Autsider666 bravo! Everything looks fantastic this will greatly improve the usability of the docs

**Comment by kamranayub** [comment]
HERO AMONG HEROES

**Pull request merged**
